Esercitazione.MVC/Controllers/MenuController.cs
using Esercitazione.Core.BusinessLayer;
using Esercitazione.Core.Entities;
using Esercitazione.MVC.Helper;
using Esercitazione.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Esercitazione.MVC.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {

        private readonly IBusinessLayer BL;

        public MenuController(IBusinessLayer bl)
        {
            BL = bl;
        }

        public IActionResult Index()
        {
            List<Menu> menu = BL.GetAllMenu();
            List<MenuViewModel> menuViewModel = new List<MenuViewModel>();

            foreach (var item in menu)
            {
                menuViewModel.Add(item.ToMenuViewModel());
            }
            return View(menuViewModel);
        }

        public IActionResult Details(int id)
        {
            var menu = BL.GetAllMenu().FirstOrDefault(m => m.Id == id);
            decimal total = menu.Piatti.Sum(p => p.Prezzo);
            var menuViewModel = menu.ToMenuViewModel();

            ViewBag.Totale = total;

            return View(menuViewModel);
        }


        [Authorize(Policy = ("Ristoratore"))]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Policy = ("Ristoratore"))]
        [HttpPost]
        public IActionResult Create(MenuViewModel menuViewModel)
        {
            if (ModelState.IsValid)
            {
                var menu = menuViewModel.ToMenu();
                var esito = BL.AggiungiMenu(menu);
                if (esito.IsOk == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = esito.Messaggio;
                    return View("ErroriBL");
                }
            }
            return View(menuViewModel);
        }
    }
}

Esercitazione.MVC/Controllers/PiattiController.cs
using Esercitazione.Core.BusinessLayer;
using Esercitazione.Core.Entities;
using Esercitazione.MVC.Helper;
using Esercitazione.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Esercitazione.MVC.Controllers
{
    [Authorize]
    public class PiattiController : Controller
    {
        private readonly IBusinessLayer BL;

        public PiattiController(IBusinessLayer bl)
        {
            BL = bl;
        }

        public IActionResult Index()
        {
            List<Piatto> piatto = BL.GetAllPiatti();
            List<PiattoViewModel> piattoViewModel = new List<PiattoViewModel>();

            foreach (var item in piatto)
            {
                piattoViewModel.Add(item.ToPiattoViewModel());
            }
            return View(piattoViewModel);
        }

        [Authorize(Policy = ("Ristoratore"))]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();

            LoadViewBag();
            ViewBag.Create = false;
            return View(piattoViewModel);
        }


        [Authorize(Policy = ("Ristoratore"))]
        [HttpPost]
        public IActionResult Edit(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                var piatto = piattoViewModel.ToPiatto();
                var esito = BL.ModificaPiatto(piatto.Id, piatto.Nome, piatto.Descrizione, piatto.TipoPiatto, piatto.Prezzo);
                if (esito.IsOk == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = esito.Messaggio;
                    return View("ErroriBL");
                }
            }
            return View(piattoViewModel);
        }

        [Authorize(Policy = ("Ristoratore"))]
        [HttpGet]
        public IActionResult Create()
        {
            LoadViewBag();
            ViewBag.Create = true;
            return View();
        }

        [Authorize(Policy = ("Ristoratore"))]
        [HttpPost]
        public IActionResult Create(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                var piatto = piattoViewModel.ToPiatto();
                var esito = BL.AggiungiPiatto(piatto);
                if (esito.IsOk == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = esito.Messaggio;
                    return View("ErroriBL");
                }
            }
            return View(piattoViewModel);
        }

        [Authorize(Policy = ("Ristoratore"))]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);
        }

        [Authorize(Policy = ("Ristoratore"))]
        [HttpPost]
        public IActionResult Delete(PiattoViewModel piattoViewModel)
        {
            var piatto = piattoViewModel.ToPiatto();
            var esito = BL.EliminaPiatto(piatto.Id);
            if (esito.IsOk == true)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.MessaggioErrore = esito.Messaggio;
                return View("ErroriDiBusiness");
            }
        }

        



        [Authorize(Policy = ("Ristoratore"))]
        public IActionResult Disaccoppia()
        {
            return View();
        }

        private void LoadViewBag()
        {
            ViewBag.TipiPiatto = new SelectList(Enum.GetValues(typeof(Tipologia)).Cast<Tipologia>().Select(t => new SelectListItem
            {
                Text = t.ToString(),
                Value = ((int)t).ToString()
            }).ToList().OrderBy(t => t.Text), "Value", "Text");
        }
    }
}

Esercitazione.MVC/Controllers/UtentiController.cs
using Esercitazione.Core.BusinessLayer;
using Esercitazione.MVC.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Esercitazione.MVC.Controllers
{
    public class UtentiController : Controller
    {
        private readonly IBusinessLayer BL;

        public UtentiController(IBusinessLayer bl)
        {
            BL = bl;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login(string returnUrl = "/")
        {
            return View(new UtenteViewModel { ReturnUrl = returnUrl });
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> LoginAsync(UtenteViewModel utenteViewModel)
        {
            if (utenteViewModel == null)
            {
                return View();
            }

            var utente = BL.GetAccount(utenteViewModel.Username);
            if (utente != null && ModelState.IsValid)
            {
                if (utente.Password == utenteViewModel.Password)
                {
                    //l'utente è autenticato"
                    var claim = new List<Claim>{

                        new Claim (ClaimTypes.Name, utente.Username),
                        new Claim (ClaimTypes.Role, utente.Ruolo.ToString())
                    };

                    var properties = new AuthenticationProperties
                    {
                        RedirectUri = utenteViewModel.ReturnUrl,
                        ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1)
                    };

                    var claimIdentity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimIdentity),
                        properties
                        );
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError(nameof(utenteViewModel.Password), "Password errata");
                    return View(utenteViewModel);
                }
            }
            else
            {
                return View(utenteViewModel);
            }

            return View();
        }

        [AllowAnonymous]
        public IActionResult Forbidden() => View();

        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }
}

Esercitazione.MVC/Views/Shared/ErroriBL.cshtml
<p>@ViewBag.MessaggioErrore</p>

Esercitazione.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Esercitazione.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Esercitazione.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Da Luigi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Piatti" asp-action="Index">Piatti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contatti">Contatti</a>
                            </li>
                        </ul>
                    </div>
                    <a asp-controller="Utenti" asp-action="Logout" class="btn btn-primary">Logout</a>
                }
                else
                {
                    <a asp-controller="Utenti" asp-action="Login" class="btn btn-primary"> Login </a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>